const PERK_LEVEL_COSTS = [1, 1, 2];

const BOARD_IMAGES = {
  "Conditional Perks": "perks/Conditional Perks/Entire Board.png",
  "Economic Perks": "perks/Economic Perks/Entire Board.png",
  "Endurance Perks": "perks/Endurance Perks/Entire Board.png",
  "Melee Perks": "perks/Melee Perks/Entire Board.png",
  "Ranged Perks": "perks/Ranged Perks/Entire Board.png",
};

const PERK_TIERS = {
  "Conditional Perks": [
    ["rampage", "march-of-the-eagle", "stand-fast", "commando"],
    ["lead-the-charge", "tough-nut", "stubborn"],
    ["bewegungskrieg", "indomitable-spirit"],
    ["undying", "lone-wolf", "unconquerable"],
  ],
  "Economic Perks": [
    ["arms-dealer", "extra-coins", "logistical-support", "silver-tongue"],
    ["military-funding", "economic-hegemon", "bounty-hunter", "investor", "risky-gains"],
    ["mutual-greed", "money-is-power", "scraps", "pariah"],
    ["blood-and-iron"],
  ],
  "Endurance Perks": [
    ["greath-athleticism", "light-feet", "quick-recovery"],
    ["protection", "field-medic", "workout"],
    ["glass-cannon", "juggernaut", "slick"],
    ["transhumanist", "herculean"],
  ],
  "Melee Perks": [
    ["frenzy", "heavy-hitter", "life-drain", "sharpness", "overpower"],
    ["last-stand", "tank-hunter", "cavalry-charge", "shock-tactic", "skirmisher-tactic"],
    ["backhand-blow", "warrior-spirit", "life-absorb", "battle-brother", "through-butter"],
    ["ordained", "thundering-advance"],
  ],
  "Ranged Perks": [
    ["armor-piercing", "high-caliber", "large-cache", "long-range", "one-shot"],
    ["decisive-blow", "fast-hand", "marksman", "buffer-zone", "focused-fire"],
    ["quality-ammo", "steel-sniper", "the-head-shall-fall", "four-eyes", "point-defense"],
    ["death-incarnate", "combined-arms"],
  ],
};

const PERKS = [
  {
    id: "bewegungskrieg",
    name: "Bewegungskrieg",
    category: "Conditional Perks",
    image: "perks/Conditional Perks/Bewegungskrieg.png",
    description: [
      "Each stack can be gained by killing enemies, can accumulate up to 8 stacks. Passively gain more duration and stack depending on how low your health is.",
      "Requires maxed Rampage. When unlocked, locks Rampage and replaces its modifiers.",
    ],
    conditions: ["Stacks from kills", "Stronger duration/stack behavior at lower health"],
    requiresMaxed: ["rampage"],
    replaces: ["rampage"],
    effects: [
      { stat: "Damage", value: 3, unit: "%", scales: false, tags: ["combat", "conditional"] },
      { stat: "Stamina Regen/Usage", value: 6, unit: "%", scales: false, tags: ["mobility", "conditional"] },
      { stat: "Max Stamina", value: 1, unit: "", scales: false, tags: ["mobility", "conditional"] },
      { stat: "Sprint Speed", value: 0.83, unit: "%", tags: ["mobility", "conditional"] },
    ],
  },
  {
    id: "commando",
    name: "Commando",
    category: "Conditional Perks",
    image: "perks/Conditional Perks/Commando.png",
    description: ["The active modifiers only apply as long as you are at least 500 studs away from the Gate."],
    conditions: ["At least 500 studs away from the Gate"],
    effects: [
      { stat: "Movement Speed (Active)", value: 4, unit: "%", tags: ["mobility", "conditional"] },
      { stat: "Health Regen (Active)", value: 4, unit: "%", tags: ["survival", "conditional"] },
      { stat: "Health Regen (Inactive)", value: -6, unit: "%", tags: ["penalty", "conditional"] },
    ],
  },
  {
    id: "indomitable-spirit",
    name: "Indomitable Spirit",
    category: "Conditional Perks",
    image: "perks/Conditional Perks/Indomitable Spirit.png",
    description: [
      "The active modifiers only apply as long as you are at least 650 studs away from the Gate.",
      "Requires maxed Commando. When unlocked, locks Commando and replaces its modifiers.",
    ],
    conditions: ["At least 650 studs away from the Gate"],
    requiresMaxed: ["commando"],
    replaces: ["commando"],
    effects: [
      { stat: "Damage (Active)", value: 6, unit: "%", tags: ["combat", "conditional"] },
      { stat: "Movement Speed (Active)", value: 13, unit: "%", levelValues: [13, 14, 15], tags: ["mobility", "conditional"] },
      { stat: "Health Regen (Active)", value: 18, unit: "%", levelValues: [18, 24, 30], tags: ["survival", "conditional"] },
      { stat: "Health Regen (Inactive)", value: -22, unit: "%", levelValues: [-22, -26, -30], tags: ["penalty", "conditional"] },
    ],
  },
  {
    id: "lead-the-charge",
    name: "Lead The Charge",
    category: "Conditional Perks",
    image: "perks/Conditional Perks/Lead The Charge.png",
    description: ["The modifiers only apply as long as a HERO is present on the map."],
    conditions: ["A HERO is present on the map"],
    effects: [
      { stat: "All Damage", value: 5, unit: "%", tags: ["combat", "conditional"] },
      { stat: "Armor", value: 5, unit: "%", tags: ["survival", "conditional"] },
    ],
  },
  {
    id: "lone-wolf",
    name: "Lone Wolf",
    category: "Conditional Perks",
    image: "perks/Conditional Perks/Lone Wolf.png",
    description: ["Increased effectiveness by 30% per player in the server. Total stats reduced by 50% per nearby ally within 200 studs."],
    conditions: ["Scales with player count", "Reduced by nearby allies within 200 studs"],
    effects: [
      { stat: "Damage", value: 4, unit: "%", tags: ["combat", "conditional"] },
      { stat: "Armor", value: 4, unit: "%", tags: ["survival", "conditional"] },
    ],
  },
  {
    id: "march-of-the-eagle",
    name: "March Of The Eagle",
    category: "Conditional Perks",
    image: "perks/Conditional Perks/March Of The Eagle.png",
    description: ["Gain 3% stats every 3 kills. Lose 3% stats every death. The bonuses reset every wave. Your stats won't go below 0."],
    conditions: ["Builds from kills", "Drops on death", "Resets every wave"],
    effects: [
      { stat: "Max Damage", value: 6, unit: "%", tags: ["combat", "conditional"] },
      { stat: "Max Armor", value: 6, unit: "%", tags: ["survival", "conditional"] },
    ],
  },
  {
    id: "rampage",
    name: "Rampage",
    category: "Conditional Perks",
    image: "perks/Conditional Perks/Rampage.png",
    description: ["Each stack can be gained by killing enemies, can accumulate up to 8 stacks. Stacks stop decaying when HP is below 66%. Passively increases progress towards the next stack when below 33%."],
    conditions: ["Stacks from kills", "Stack decay stops below 66% HP", "Progress increases below 33% HP"],
    effects: [
      { stat: "Damage", value: 1, unit: "%", tags: ["combat", "conditional"] },
      { stat: "Stamina Regen/Usage", value: 2, unit: "%", tags: ["mobility", "conditional"] },
      { stat: "Max Stamina", value: 0.3, unit: "", tags: ["mobility", "conditional"] },
    ],
  },
  {
    id: "stand-fast",
    name: "Stand Fast",
    category: "Conditional Perks",
    image: "perks/Conditional Perks/Stand Fast.png",
    description: ["The active modifiers apply as long as you are less than 350 studs from the Gate or receiving buffs from Tier 3 Sandbags."],
    conditions: ["Less than 350 studs from the Gate", "Or receiving Tier 3 Sandbag buffs"],
    effects: [
      { stat: "Damage", value: 4, unit: "%", tags: ["combat", "conditional"] },
      { stat: "Armor", value: 4, unit: "%", tags: ["survival", "conditional"] },
    ],
  },
  {
    id: "stubborn",
    name: "Stubborn",
    category: "Conditional Perks",
    image: "perks/Conditional Perks/Stubborn.png",
    description: ["Increased health and stamina regeneration when below 50% HP."],
    conditions: ["Below 50% HP"],
    effects: [
      { stat: "HP Regen", value: 5, unit: "%", tags: ["survival", "conditional"] },
      { stat: "Stamina Regen", value: 10, unit: "%", tags: ["mobility", "conditional"] },
    ],
  },
  {
    id: "tough-nut",
    name: "Tough Nut",
    category: "Conditional Perks",
    image: "perks/Conditional Perks/Tough Nut.png",
    description: ["The modifier only applies if your health is above 85%."],
    conditions: ["Health above 85%"],
    effects: [
      { stat: "Health Regen", value: 125, unit: "%", op: "x", levelValues: [125, 150, 175], tags: ["survival", "conditional"] },
      { stat: "Health Regen (Max)", value: 400, unit: "/s", tags: ["survival", "conditional"] },
    ],
  },
  {
    id: "unconquerable",
    name: "Unconquerable",
    category: "Conditional Perks",
    image: "perks/Conditional Perks/Unconquerable.png",
    description: ["Requires maxed Indomitable Spirit and maxed Stand Fast. Indomitable Spirit already requires maxed Commando. This perk is mutually-exclusive with Undying."],
    conditions: ["Adjusts the active ranges of Commando/Indomitable Spirit and Stand Fast"],
    requiresMaxed: ["indomitable-spirit", "stand-fast"],
    mutuallyExclusive: ["undying"],
    effects: [
      { stat: "Commando/Indomitable Spirit Range", value: -100, unit: "", tags: ["range", "conditional"] },
      { stat: "Stand Fast Range", value: 100, unit: "", tags: ["range", "conditional"] },
    ],
  },
  {
    id: "undying",
    name: "Undying",
    category: "Conditional Perks",
    image: "perks/Conditional Perks/Undying.png",
    description: [
      "Gain temporary invincibility when below 15% HP. If you would survive a lethal hit, this perk's invincibility duration is halved and passive HP regen is disabled during that time.",
      "This perk will not trigger if the lethal hit you would receive is stronger than your max HP.",
    ],
    conditions: ["Triggers below 15% HP", "Special lethal-hit rules"],
    mutuallyExclusive: ["unconquerable"],
    effects: [
      { stat: "Invincibility", value: 1, unit: "s", tags: ["survival", "conditional"] },
    ],
  },
  {
    id: "arms-dealer",
    name: "Arms Dealer",
    category: "Economic Perks",
    image: "perks/Economic Perks/Arms Dealer.png",
    description: ["Purchasing an item will return some coins."],
    effects: [{ stat: "Return", value: 2, unit: "%", tags: ["economy"] }],
  },
  {
    id: "blood-and-iron",
    name: "Blood and Iron",
    category: "Economic Perks",
    image: "perks/Economic Perks/Blood and Iron.png",
    description: ["Requires 44 points invested in Economic Perks."],
    categoryRequirement: { category: "Economic Perks", points: 44 },
    synergies: ["Modifies Money Is Power cap", "Modifies Investor cap", "Improves Military Funding return"],
    effects: [
      { stat: "Money Is Power Cap", value: -5, unit: "%", tags: ["economy", "synergy"] },
      { stat: "Investor Cap", value: 4500, unit: "", levelValues: [4500, 5000, 5500], tags: ["economy", "synergy"] },
      { stat: "Mil. Funding Return", value: 2, unit: "%", tags: ["economy", "synergy"] },
      { stat: "Death Penalty", value: 10, unit: "%", tags: ["penalty"] },
    ],
  },
  {
    id: "bounty-hunter",
    name: "Bounty Hunter",
    category: "Economic Perks",
    image: "perks/Economic Perks/Bounty Hunter.png",
    description: ["Gain extra coins per kill depending on how many coins you have. Each additional player with maxed Bounty Hunter while holding at least 750 coins increases the bonus by 1 coin."],
    conditions: ["Coins per kill depends on current coins", "Extra player bonus requires other maxed Bounty Hunter users"],
    effects: [
      { stat: "Coins per Kill (>750 Coins)", value: 2, unit: "", tags: ["economy", "conditional"] },
      { stat: "Coins per Kill (>1500 Coins)", value: 3, unit: "", tags: ["economy", "conditional"] },
      { stat: "Coins per Kill (>3000 Coins)", value: 4, unit: "", tags: ["economy", "conditional"] },
      { stat: "Coins per Kill (>6000 Coins)", value: 5, unit: "", tags: ["economy", "conditional"] },
      { stat: "Sell", value: -1, unit: "%", tags: ["penalty", "economy"] },
    ],
  },
  {
    id: "economic-hegemon",
    name: "Economic Hegemon",
    category: "Economic Perks",
    image: "perks/Economic Perks/Economic Hegemon.png",
    description: ["This perk is mutually-exclusive with Extra Coins."],
    mutuallyExclusive: ["extra-coins"],
    effects: [
      { stat: "Damage & Armor", value: -5, unit: "%", tags: ["penalty", "combat", "survival"] },
      { stat: "Coins", value: 2, unit: "%", tags: ["economy"] },
      { stat: "Return", value: 1, unit: "%", tags: ["economy"] },
      { stat: "Sell", value: 1, unit: "%", tags: ["economy"] },
    ],
  },
  {
    id: "extra-coins",
    name: "Extra Coins",
    category: "Economic Perks",
    image: "perks/Economic Perks/Extra Coins.png",
    description: ["This perk is mutually-exclusive with Economic Hegemon."],
    mutuallyExclusive: ["economic-hegemon"],
    effects: [{ stat: "Coins", value: 2, unit: "%", tags: ["economy"] }],
  },
  {
    id: "investor",
    name: "Investor",
    category: "Economic Perks",
    image: "perks/Economic Perks/Investor.png",
    description: ["Gain interest every wave. The maximum amount affected is limited to 4000 coins before modifiers."],
    effects: [{ stat: "Interest", value: 4, unit: "%", tags: ["economy"] }],
  },
  {
    id: "logistical-support",
    name: "Logistical Support",
    category: "Economic Perks",
    image: "perks/Economic Perks/Logistical Support.png",
    description: ["Bonus: instantly gain more coins if Wave 1 and more have already been beaten."],
    conditions: ["Bonus coins if at least Wave 1 has been beaten"],
    effects: [{ stat: "Wave Reward", value: 3, unit: "%", tags: ["economy"] }],
  },
  {
    id: "military-funding",
    name: "Military Funding",
    category: "Economic Perks",
    image: "perks/Economic Perks/Military Funding.png",
    description: ["Upgrading Robloxian Defense Force or Titan Turret will return some money. This does not apply to normal gear purchases. Stacks at half effectiveness with other players."],
    conditions: ["Applies only to RDF or Titan Turret upgrades", "Does not apply to normal gear purchases", "Stacks at half effectiveness with other players"],
    effects: [{ stat: "Upgrade Return", value: 2, unit: "%", tags: ["economy"] }],
  },
  {
    id: "money-is-power",
    name: "Money Is Power",
    category: "Economic Perks",
    image: "perks/Economic Perks/Money Is Power.png",
    description: ["The modifiers scale off your balance, up to a maximum at 2000 coins in Wave 1 and 13500 coins in Wave 10. A lower threshold starts increasing from 250 at Wave 5 up to 1500 at Wave 10. Below thresholds, you incur penalties relative to half of the perk's max modifiers."],
    conditions: ["Scales with current balance and wave", "Can become a penalty below the balance threshold"],
    effects: [
      { stat: "Damage", value: 10, unit: "%", tags: ["combat", "conditional"] },
      { stat: "Armor", value: 10, unit: "%", tags: ["survival", "conditional"] },
    ],
  },
  {
    id: "mutual-greed",
    name: "Mutual Greed",
    category: "Economic Perks",
    image: "perks/Economic Perks/Mutual Greed.png",
    description: ["Bonus: instantly gain more coins if Wave 1 and more have already been beaten. The effects of this perk scale upwards with the game's difficulty. This perk is only unlockable on Wave 1 or if you have participated in at least 1 wave."],
    conditions: ["Difficulty scaling", "Unlockable on Wave 1 or after participating in at least 1 wave"],
    effects: [
      { stat: "Enemy HP", value: 3, unit: "%", tags: ["penalty"] },
      { stat: "Coins", value: 2, unit: "%", tags: ["economy"] },
      { stat: "Wave Reward", value: 3, unit: "%", tags: ["economy"] },
    ],
  },
  {
    id: "pariah",
    name: "Pariah",
    category: "Economic Perks",
    image: "perks/Economic Perks/Pariah.png",
    description: ["Requires maxed Bounty Hunter. Buffs Bounty Hunter. Increase Bounty Hunter's multiplayer coin bonus to 2 coins per eligible player at max Pariah. Equipment Maintenance only affects guns, melee, armor, and engineer equipment."],
    requiresMaxed: ["bounty-hunter"],
    synergies: ["Buffs Bounty Hunter multiplayer coin bonus"],
    effects: [
      { stat: "Coins per Kill (>9000 Coins)", value: 24, unit: "", levelValues: [24, 30, 36], tags: ["economy", "conditional"] },
      { stat: "Coins per Kill (<9000 Coins)", value: 2, unit: "", tags: ["economy", "conditional"] },
      { stat: "Equipment Maintenance", value: 10, unit: "%", tags: ["penalty", "economy"] },
    ],
  },
  {
    id: "risky-gains",
    name: "Risky Gains",
    category: "Economic Perks",
    image: "perks/Economic Perks/Risky Gains.png",
    description: ["Bonus: instantly gain more coins if Wave 1 and more have already been beaten."],
    conditions: ["Bonus coins if at least Wave 1 has been beaten"],
    effects: [
      { stat: "Death Penalty", value: 10, unit: "%", tags: ["penalty"] },
      { stat: "Coins", value: 2, unit: "%", tags: ["economy"] },
      { stat: "Wave Reward", value: 1, unit: "%", tags: ["economy"] },
    ],
  },
  {
    id: "scraps",
    name: "Scraps",
    category: "Economic Perks",
    image: "perks/Economic Perks/Scraps.png",
    description: ["Destroying mechanical enemies such as tanks and helicopters will earn extra coins. Capturing mechanical enemy vehicles successfully will also earn extra coins."],
    conditions: ["Mechanical enemy kills, such as tanks and helicopters", "Mechanical enemy vehicle captures"],
    effects: [
      { stat: "Coin per Kill", value: 5, unit: "", tags: ["economy", "conditional"] },
      { stat: "Coin per Capture", value: 10, unit: "", tags: ["economy", "conditional"] },
    ],
  },
  {
    id: "silver-tongue",
    name: "Silver Tongue",
    category: "Economic Perks",
    image: "perks/Economic Perks/Silver Tongue.png",
    description: ["Selling will yield more coins."],
    effects: [{ stat: "Sell", value: 2, unit: "%", tags: ["economy"] }],
  },
  {
    id: "field-medic",
    name: "Field Medic",
    category: "Endurance Perks",
    image: "perks/Endurance Perks/Field Medic.png",
    effects: [
      { stat: "Medkit Cooldown (Self)", value: -10, unit: "%", tags: ["support", "survival"] },
      { stat: "Medkit Cooldown (Others)", value: -8, unit: "%", tags: ["support", "survival"] },
    ],
  },
  {
    id: "glass-cannon",
    name: "Glass Cannon",
    category: "Endurance Perks",
    image: "perks/Endurance Perks/Glass Cannon.png",
    description: ["This perk is mutually-exclusive with Juggernaut."],
    mutuallyExclusive: ["juggernaut"],
    effects: [
      { stat: "Base HP", value: -20, unit: "", tags: ["penalty", "survival"] },
      { stat: "Damage", value: 8, unit: "%", tags: ["combat"] },
      { stat: "Crit Chance", value: 1, unit: "%", tags: ["combat"] },
    ],
  },
  {
    id: "greath-athleticism",
    name: "Greath Athleticism",
    category: "Endurance Perks",
    image: "perks/Endurance Perks/Greath Athleticism.png",
    effects: [{ stat: "Max Stamina", value: 1, unit: "", tags: ["mobility"] }],
  },
  {
    id: "herculean",
    name: "Herculean",
    category: "Endurance Perks",
    image: "perks/Endurance Perks/Herculean.png",
    description: ["Having at least 200 Max Weight will activate these modifiers."],
    conditions: ["At least 200 Max Weight"],
    effects: [
      { stat: "Base HP", value: 5, unit: "", tags: ["survival", "conditional"] },
      { stat: "Damage", value: 3, unit: "%", tags: ["combat", "conditional"] },
    ],
  },
  {
    id: "juggernaut",
    name: "Juggernaut",
    category: "Endurance Perks",
    image: "perks/Endurance Perks/Juggernaut.png",
    description: ["This perk is mutually-exclusive with Glass Cannon."],
    mutuallyExclusive: ["glass-cannon"],
    effects: [
      { stat: "Base HP", value: 20, unit: "", tags: ["survival"] },
      { stat: "Damage", value: -5, unit: "%", tags: ["penalty", "combat"] },
      { stat: "Movement Speed", value: -7, unit: "%", tags: ["penalty", "mobility"] },
    ],
  },
  {
    id: "light-feet",
    name: "Light Feet",
    category: "Endurance Perks",
    image: "perks/Endurance Perks/Light Feet.png",
    effects: [{ stat: "Movement Speed", value: 4, unit: "%", tags: ["mobility"] }],
  },
  {
    id: "protection",
    name: "Protection",
    category: "Endurance Perks",
    image: "perks/Endurance Perks/Protection.png",
    effects: [{ stat: "Armor", value: 5, unit: "%", tags: ["survival"] }],
  },
  {
    id: "quick-recovery",
    name: "Quick Recovery",
    category: "Endurance Perks",
    image: "perks/Endurance Perks/Quick Recovery.png",
    effects: [{ stat: "Health Regen", value: 5, unit: "%", tags: ["survival"] }],
  },
  {
    id: "slick",
    name: "Slick",
    category: "Endurance Perks",
    image: "perks/Endurance Perks/Slick.png",
    description: ["Requires maxed Light Feet. When unlocked, locks Light Feet."],
    requiresMaxed: ["light-feet"],
    locks: ["light-feet"],
    effects: [
      { stat: "Base HP", value: -15, unit: "", tags: ["penalty", "survival"] },
      { stat: "Movement Speed", value: 4, unit: "%", tags: ["mobility"] },
      { stat: "Weight Penalty", value: -5, unit: "%", tags: ["mobility"] },
    ],
  },
  {
    id: "transhumanist",
    name: "Transhumanist",
    category: "Endurance Perks",
    image: "perks/Endurance Perks/Transhumanist.png",
    effects: [{ stat: "DMG Per Augment", value: 1, unit: "%", levelValues: [1, 1.5, 2], tags: ["combat", "conditional"] }],
  },
  {
    id: "workout",
    name: "Workout",
    category: "Endurance Perks",
    image: "perks/Endurance Perks/Workout.png",
    effects: [{ stat: "Max Weight", value: 5, unit: "", tags: ["survival"] }],
  },
  {
    id: "backhand-blow",
    name: "Backhand Blow",
    category: "Melee Perks",
    image: "perks/Melee Perks/Backhand Blow.png",
    description: ["Deal extra damage on your next attack after recovering from 20% HP to 70% HP."],
    conditions: ["Next attack after recovering from 20% HP to 70% HP"],
    effects: [{ stat: "Melee Damage", value: 150, unit: "%", op: "x", levelValues: [150, 200, 250], tags: ["combat", "melee", "conditional"] }],
  },
  {
    id: "battle-brother",
    name: "Battle Brother",
    category: "Melee Perks",
    image: "perks/Melee Perks/Battle Brother.png",
    description: ["A nearby player within 75 studs with the same perk or an NPC with at least 3000 x Wave Count HP will activate this perk. Both of you must be above 50% HP. If both of you have at least 120% melee damage modifiers, the range increases to 150 studs."],
    conditions: ["Nearby same-perk player or qualifying NPC", "Both above 50% HP"],
    effects: [
      { stat: "Armor", value: 4, unit: "%", tags: ["survival", "conditional"] },
      { stat: "Melee Damage", value: 3, unit: "%", tags: ["combat", "melee", "conditional"] },
    ],
  },
  {
    id: "cavalry-charge",
    name: "Cavalry Charge",
    category: "Melee Perks",
    image: "perks/Melee Perks/Cavalry Charge.png",
    description: ["The damage modifier only applies when sprinting. Must be holding a melee weapon to benefit from the modifiers."],
    conditions: ["Sprinting", "Holding a melee weapon"],
    effects: [
      { stat: "Melee Damage", value: 8, unit: "%", tags: ["combat", "melee", "conditional"] },
      { stat: "Sprint Speed", value: 5, unit: "%", tags: ["mobility", "conditional"] },
      { stat: "Low Health Speed Penalty", value: 7, unit: "%", tags: ["penalty", "mobility"] },
    ],
  },
  {
    id: "frenzy",
    name: "Frenzy",
    category: "Melee Perks",
    image: "perks/Melee Perks/Frenzy.png",
    description: ["Gain a stack per hit which decays after 5 seconds. Resets on death."],
    conditions: ["Stacks per hit", "Stacks decay after 5 seconds"],
    effects: [{ stat: "Melee Damage", value: 2, unit: "%", tags: ["combat", "melee", "conditional"] }],
  },
  {
    id: "heavy-hitter",
    name: "Heavy Hitter",
    category: "Melee Perks",
    image: "perks/Melee Perks/Heavy Hitter.png",
    effects: [
      { stat: "Melee Critical Chance", value: 1, unit: "%", tags: ["combat", "melee"] },
      { stat: "Melee Critical Damage", value: 105, unit: "%", op: "x", levelValues: [105, 110, 115], tags: ["combat", "melee"] },
    ],
  },
  {
    id: "last-stand",
    name: "Last Stand",
    category: "Melee Perks",
    image: "perks/Melee Perks/Last Stand.png",
    description: ["These modifiers are only active when health is below 50%. Must be holding a melee weapon to benefit from the modifiers."],
    conditions: ["Health below 50%", "Holding a melee weapon"],
    effects: [
      { stat: "Melee Damage", value: 10, unit: "%", tags: ["combat", "melee", "conditional"] },
      { stat: "Health Regen", value: 5, unit: "%", tags: ["survival", "conditional"] },
    ],
  },
  {
    id: "life-absorb",
    name: "Life Absorb",
    category: "Melee Perks",
    image: "perks/Melee Perks/Life Absorb.png",
    description: ["Each successful hit on non-mechanical enemies will regenerate some health. Requires maxed Life Drain. When unlocked, locks Life Drain and replaces its modifiers."],
    conditions: ["Successful hits on non-mechanical enemies"],
    requiresMaxed: ["life-drain"],
    replaces: ["life-drain"],
    effects: [
      { stat: "Stamina", value: -0.1, unit: "", tags: ["penalty", "melee", "conditional"] },
      { stat: "Lifesteal", value: 1.4, unit: "%", levelValues: [1.4, 1.7, 2], tags: ["survival", "melee", "conditional"] },
    ],
  },
  {
    id: "life-drain",
    name: "Life Drain",
    category: "Melee Perks",
    image: "perks/Melee Perks/Life Drain.png",
    description: ["Each successful hit on non-mechanical enemies will regenerate some health."],
    conditions: ["Successful hits on non-mechanical enemies"],
    effects: [{ stat: "Lifesteal", value: 0.2, unit: "%", tags: ["survival", "melee", "conditional"] }],
  },
  {
    id: "ordained",
    name: "Ordained",
    category: "Melee Perks",
    image: "perks/Melee Perks/Ordained.png",
    description: ["Requires 24 points invested in Melee Perks. The perk becomes inactive if the requirement is no longer met. Gain extra stats every time a critical hit is dealt. Stacks up to 5 times, each stack decays after 60 seconds. Intermission prevents this decay."],
    categoryRequirement: { category: "Melee Perks", points: 24 },
    conditions: ["Critical hits", "Stacks up to 5", "Stacks decay after 60 seconds"],
    effects: [
      { stat: "HP Per Crit", value: 3.3, unit: "", tags: ["survival", "melee", "conditional"] },
      { stat: "Melee DMG Per Crit", value: 1.3, unit: "%", tags: ["combat", "melee", "conditional"] },
      { stat: "Regen Per Crit", value: 1.3, unit: "%", tags: ["survival", "melee", "conditional"] },
    ],
  },
  {
    id: "overpower",
    name: "Overpower",
    category: "Melee Perks",
    image: "perks/Melee Perks/Overpower.png",
    description: ["Deal extra damage if the enemy HP percentage is lower than yours by 20%."],
    conditions: ["Enemy HP percentage is at least 20% lower than yours"],
    effects: [{ stat: "Melee Damage", value: 106, unit: "%", op: "x", levelValues: [106, 112, 118], tags: ["combat", "melee", "conditional"] }],
  },
  {
    id: "sharpness",
    name: "Sharpness",
    category: "Melee Perks",
    image: "perks/Melee Perks/Sharpness.png",
    effects: [{ stat: "Melee Damage", value: 5, unit: "%", tags: ["combat", "melee"] }],
  },
  {
    id: "shock-tactic",
    name: "Shock Tactic",
    category: "Melee Perks",
    image: "perks/Melee Perks/Shock Tactic.png",
    description: ["Every successful hit will deplete stamina. Must be holding a melee weapon to benefit from the modifiers. This perk is mutually-exclusive with Skirmisher Tactic."],
    conditions: ["Successful hits deplete stamina", "Holding a melee weapon"],
    mutuallyExclusive: ["skirmisher-tactic"],
    effects: [
      { stat: "Stamina", value: -0.2, unit: "", tags: ["penalty", "melee", "conditional"] },
      { stat: "Melee Damage", value: 5, unit: "%", tags: ["combat", "melee", "conditional"] },
      { stat: "Armor", value: 2, unit: "%", tags: ["survival", "melee", "conditional"] },
      { stat: "Regen", value: 5, unit: "%", tags: ["survival", "melee", "conditional"] },
    ],
  },
  {
    id: "skirmisher-tactic",
    name: "Skirmisher Tactic",
    category: "Melee Perks",
    image: "perks/Melee Perks/Skirmisher Tactic.png",
    description: ["Every successful hit will restore stamina. This perk is mutually-exclusive with Shock Tactic."],
    conditions: ["Successful hits restore stamina"],
    mutuallyExclusive: ["shock-tactic"],
    effects: [{ stat: "Stamina", value: 0.1, unit: "", tags: ["mobility", "melee", "conditional"] }],
  },
  {
    id: "tank-hunter",
    name: "Tank Hunter",
    category: "Melee Perks",
    image: "perks/Melee Perks/Tank Hunter.png",
    description: ["This modifier only applies on enemy vehicles."],
    conditions: ["Enemy vehicles"],
    effects: [{ stat: "Melee Damage", value: 106, unit: "%", op: "x", levelValues: [106, 112, 118], tags: ["combat", "melee", "conditional"] }],
  },
  {
    id: "through-butter",
    name: "Through Butter",
    category: "Melee Perks",
    image: "perks/Melee Perks/Through Butter.png",
    description: ["Decreases the damage dropoff from attacking multiple enemies at once."],
    effects: [{ stat: "Damage Dropoff", value: -12, unit: "%", tags: ["combat", "melee"] }],
  },
  {
    id: "thundering-advance",
    name: "Thundering Advance",
    category: "Melee Perks",
    image: "perks/Melee Perks/Thundering Advance.png",
    description: ["Requires 24 points invested in Melee Perks. Must be sprinting and holding your melee weapon without swinging to benefit from the effects. Swinging your melee weapon reduces your dodge chance by x4. The Battle Brother range bonus is always active."],
    categoryRequirement: { category: "Melee Perks", points: 24 },
    conditions: ["Sprinting", "Holding melee weapon without swinging"],
    synergies: ["Increases Battle Brother range"],
    effects: [
      { stat: "Dodge Chance", value: 7, unit: "%", levelValues: [7, 11, 15], tags: ["survival", "melee", "conditional"] },
      { stat: "Dodge Chance (>10 Stam.)", value: 10, unit: "%", levelValues: [10, 13, 16], tags: ["survival", "melee", "conditional"] },
      { stat: "Dodge Chance (Per Augment)", value: 1, unit: "%", scales: false, tags: ["survival", "melee", "conditional"] },
      { stat: "Battle Brothers Range", value: 20, unit: "", tags: ["synergy", "melee"] },
    ],
  },
  {
    id: "warrior-spirit",
    name: "Warrior Spirit",
    category: "Melee Perks",
    image: "perks/Melee Perks/Warrior Spirit.png",
    description: ["These modifiers are only active when health is above 50%."],
    conditions: ["Health above 50%"],
    effects: [{ stat: "Melee Damage", value: 8, unit: "%", tags: ["combat", "melee", "conditional"] }],
  },
  {
    id: "armor-piercing",
    name: "Armor Piercing",
    category: "Ranged Perks",
    image: "perks/Ranged Perks/Armor Piercing.png",
    effects: [
      { stat: "Ranged Damage", value: 7, unit: "%", tags: ["combat", "ranged"] },
      { stat: "Headshot Damage", value: -10, unit: "%", tags: ["penalty", "ranged"] },
    ],
  },
  {
    id: "buffer-zone",
    name: "Buffer Zone",
    category: "Ranged Perks",
    image: "perks/Ranged Perks/Buffer Zone.png",
    description: ["Receive full damage modifier as long as any enemy is 1000 studs away from the Core. The damage modifier slowly reduces to 0% as any enemy gets closer to 300 studs from the Core."],
    conditions: ["Enemy distance from Core"],
    effects: [{ stat: "Ranged Damage", value: 8, unit: "%", tags: ["combat", "ranged", "conditional"] }],
  },
  {
    id: "combined-arms",
    name: "Combined Arms",
    category: "Ranged Perks",
    image: "perks/Ranged Perks/Combined Arms.png",
    description: ["Requires 24 points invested in Ranged Perks. Each additional Combined Arms user has its effectiveness halved. Mutually exclusive with Death Incarnate. Other players with at least 16 Melee Perk points receive an HP buff if you have less than 16 Melee Perks. Every additional melee player receiving the buff reduces its effectiveness by 7.5 HP, but you get +4% damage per melee player in return."],
    categoryRequirement: { category: "Ranged Perks", points: 24 },
    mutuallyExclusive: ["death-incarnate"],
    conditions: ["Team composition dependent"],
    effects: [
      { stat: "Base HP (Others)", value: 10, unit: "", tags: ["support", "conditional"] },
      { stat: "Base HP (Others, Additional)", value: -7.5, unit: "", scales: false, tags: ["penalty", "support", "conditional"] },
      { stat: "Ranged Damage (You)", value: 2, unit: "%", tags: ["combat", "ranged", "conditional"] },
      { stat: "Ranged Damage (You, Additional)", value: 4, unit: "%", scales: false, tags: ["combat", "ranged", "conditional"] },
    ],
  },
  {
    id: "death-incarnate",
    name: "Death Incarnate",
    category: "Ranged Perks",
    image: "perks/Ranged Perks/Death Incarnate.png",
    description: ["Requires 24 points invested in Ranged Perks. The perk becomes inactive if the requirement is no longer met. Mutually exclusive with Combined Arms. Increased base walkspeed and HP regen when holding a ranged weapon."],
    categoryRequirement: { category: "Ranged Perks", points: 24 },
    mutuallyExclusive: ["combined-arms"],
    conditions: ["Holding a ranged weapon"],
    effects: [
      { stat: "Walkspeed", value: 3, unit: "%", tags: ["mobility", "ranged", "conditional"] },
      { stat: "HP Regen", value: 5, unit: "%", tags: ["survival", "ranged", "conditional"] },
      { stat: "Headshot Damage", value: 5, unit: "%", tags: ["combat", "ranged", "conditional"] },
    ],
  },
  {
    id: "decisive-blow",
    name: "Decisive Blow",
    category: "Ranged Perks",
    image: "perks/Ranged Perks/Decisive Blow.png",
    effects: [
      { stat: "Ranged Critical Chance", value: 1, unit: "%", tags: ["combat", "ranged"] },
      { stat: "Ranged Critical Damage", value: 105, unit: "%", op: "x", levelValues: [105, 110, 115], tags: ["combat", "ranged"] },
    ],
  },
  {
    id: "fast-hand",
    name: "Fast Hand",
    category: "Ranged Perks",
    image: "perks/Ranged Perks/Fast Hand.png",
    description: ["Reload Speed modifier applies at 50.0% effectiveness for single-shot weapons."],
    conditions: ["Single-shot weapons get 50% effectiveness"],
    effects: [{ stat: "Reload Speed", value: 10, unit: "%", tags: ["ranged", "utility"] }],
  },
  {
    id: "focused-fire",
    name: "Focused Fire",
    category: "Ranged Perks",
    image: "perks/Ranged Perks/Focused Fire.png",
    description: ["You and other players gain increased damage towards a target being attacked by you. The effect expires after 10 seconds if the target is not being attacked by you. Does not stack. This buff affects only ranged attacks."],
    conditions: ["Target recently attacked by you", "Ranged attacks only", "Does not stack"],
    effects: [{ stat: "Ranged Damage", value: 5, unit: "%", tags: ["combat", "ranged", "conditional"] }],
  },
  {
    id: "four-eyes",
    name: "Four Eyes",
    category: "Ranged Perks",
    image: "perks/Ranged Perks/Four Eyes.png",
    description: ["This perk is mutually-exclusive with Long Range. Increased HP regen when holding a ranged weapon."],
    mutuallyExclusive: ["long-range"],
    conditions: ["Holding a ranged weapon for HP Regen"],
    effects: [
      { stat: "Ranged Damage", value: 2, unit: "%", tags: ["combat", "ranged"] },
      { stat: "HP Regen", value: 5, unit: "%", tags: ["survival", "ranged", "conditional"] },
      { stat: "Max Range", value: -10, unit: "%", tags: ["penalty", "ranged"] },
    ],
  },
  {
    id: "high-caliber",
    name: "High Caliber",
    category: "Ranged Perks",
    image: "perks/Ranged Perks/High Caliber.png",
    effects: [{ stat: "Ranged Damage", value: 5, unit: "%", tags: ["combat", "ranged"] }],
  },
  {
    id: "large-cache",
    name: "Large Cache",
    category: "Ranged Perks",
    image: "perks/Ranged Perks/Large Cache.png",
    description: ["This perk is mutually-exclusive with Quality Ammo."],
    mutuallyExclusive: ["quality-ammo"],
    effects: [
      { stat: "Ammo", value: 10, unit: "%", tags: ["ranged", "utility"] },
      { stat: "Mag", value: 10, unit: "%", tags: ["ranged", "utility"] },
    ],
  },
  {
    id: "long-range",
    name: "Long Range",
    category: "Ranged Perks",
    image: "perks/Ranged Perks/Long Range.png",
    description: ["This perk is mutually-exclusive with Four Eyes."],
    mutuallyExclusive: ["four-eyes"],
    effects: [
      { stat: "Range", value: 2, unit: "%", tags: ["ranged", "utility"] },
      { stat: "Projectile Speed", value: 15, unit: "%", tags: ["ranged", "utility"] },
    ],
  },
  {
    id: "marksman",
    name: "Marksman",
    category: "Ranged Perks",
    image: "perks/Ranged Perks/Marksman.png",
    effects: [
      { stat: "Spread", value: -5, unit: "%", tags: ["ranged", "utility"] },
      { stat: "Recoil", value: -5, unit: "%", tags: ["ranged", "utility"] },
    ],
  },
  {
    id: "one-shot",
    name: "One Shot",
    category: "Ranged Perks",
    image: "perks/Ranged Perks/One Shot.png",
    effects: [{ stat: "Headshot Damage", value: 10, unit: "%", tags: ["combat", "ranged"] }],
  },
  {
    id: "point-defense",
    name: "Point Defense",
    category: "Ranged Perks",
    image: "perks/Ranged Perks/Point Defense.png",
    description: ["Deal extra damage to all aerial targets. Deal extra damage to all targets within 600 studs of the Core."],
    conditions: ["Aerial targets", "Targets within 600 studs of the Core"],
    effects: [
      { stat: "AA Damage", value: 4, unit: "%", tags: ["combat", "ranged", "conditional"] },
      { stat: "Ranged Damage", value: 6, unit: "%", tags: ["combat", "ranged", "conditional"] },
    ],
  },
  {
    id: "quality-ammo",
    name: "Quality Ammo",
    category: "Ranged Perks",
    image: "perks/Ranged Perks/Quality Ammo.png",
    description: ["This perk is mutually-exclusive with Large Cache."],
    mutuallyExclusive: ["large-cache"],
    effects: [
      { stat: "Ranged Damage", value: 7, unit: "%", tags: ["combat", "ranged"] },
      { stat: "Ammo", value: -10, unit: "%", tags: ["penalty", "ranged"] },
      { stat: "Mag", value: -10, unit: "%", tags: ["penalty", "ranged"] },
      { stat: "Throwable/DATL Recharge Speed", value: -5, unit: "%", tags: ["penalty", "utility"] },
    ],
  },
  {
    id: "steel-sniper",
    name: "Steel Sniper",
    category: "Ranged Perks",
    image: "perks/Ranged Perks/Steel Sniper.png",
    description: ["Deal extra damage to targets over 250 studs away."],
    conditions: ["Targets over 250 studs away"],
    effects: [{ stat: "Ranged Damage", value: 8, unit: "%", tags: ["combat", "ranged", "conditional"] }],
  },
  {
    id: "the-head-shall-fall",
    name: "The Head Shall Fall",
    category: "Ranged Perks",
    image: "perks/Ranged Perks/The Head Shall Fall.png",
    description: ["Increased critical chance on successful headshots."],
    conditions: ["Successful headshots"],
    effects: [{ stat: "Ranged Critical Chance", value: 120, unit: "%", op: "x", tags: ["combat", "ranged", "conditional"] }],
  },
];
